version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eddie-bot
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./.env.local:/app/.env.local
