version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-container
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - MENSAPLUS_BOT_TOKEN=${DISCORD_TOKEN}
