version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mensa-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./.env:/app/.env
